version: "3.8"

services:
  nginx:
    image: rivce/custom-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./monitoring/nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    build: ./app
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
